### ISSUE TITLE
按照readme的作法，還是沒辦法串到資料

### ISSUE THREAD

**Issue by huanyichuang** [SurveyCake/webhook#3]
想跟作者確認一下，根據我對 readme 的理解，
1. 設定 webhook url (假設為 https://www.domain.com/decrypt.php)，其中 decrypt.php 的原始碼如下
`<?php
$key = '問卷的Hash Key';
$iv = '問卷的IV Key';
$dat = file_get_contents($_POST['url']);
$json = openssl_decrypt(
	$dat,
	'AES-128-CBC',
	$key,
	false,
	$iv
);
// user answer json
print_r( json_decode($json) ); `

2. 當我送出問卷後，decrypt.php 就會直接顯示 JSON 的作答內容了嗎？從上面的code來看，在傳送post資料過來的同時，應該是傳送url這個參數應該是已經包含svid與hash兩個參數的完整網址，但是在送出問卷，將感謝頁轉址按鈕連結到 https://www.domain.com/decrypt.php 時，卻看不到任何填答的資料。不知道是哪個環節出錯了呢？

**Comment by jessy1092** [comment]
webhook 是填完答案之後，會 post `svid`, `hash`到你指定的 server ，流程大概如下：

1. 填入  https://www.domain.com/decrypt.php ，每次填答完，會收一個 POST request ，帶 `svid ` 跟 `hash`

2. `$_POST['svid']` 跟 `$_POST['hash']` 會拿到傳過來的資料，可以存進資料庫，或是馬上發 request 去問問卷解答

3. 發 request 去 `'https://www.surveycake.com/webhook/v0/'.$svid.'/'.$hash` 要使用者的答案，然後使用 `key`, `iv` 解出 （decrypt.php 裡範例是屬於這段）

所以根據以上流程  直接訪問  https://www.domain.com/decrypt.php 是看不到結果的， server 端要處理 webhook 接收到的資料，然後做一個前端頁面來呈現

**Comment by huanyichuang** [comment]
@jessy1092 感謝您的回答，重新根據您的方法測試後就可以取得資料了！謝謝！
