### ISSUE TITLE
可以提供一組加解密結果，包含 Hash key 和 IV key 的範例嗎？

### ISSUE THREAD

**Issue by badboy99tw** [SurveyCake/webhook#6]
README 的加解密資料似乎沒有提供 Hash key 和 IV key
請問可以提供一組資料方便測試嗎？

謝謝

**Comment by wubaibai** [comment]
你好，您可以在 SurveyCake 登入後建立一份問卷，即可在該份問卷的 “自訂感謝頁” 功能，找到該份問卷專屬的 Hash key 和 IV key。

**Comment by badboy99tw** [comment]
了解～

只是覺得 README 已經提供加密填答結果了，如果也有 Hash key 和 IV key，那就可以透過 README 的資料實作解密的部分，就不用在 SurveyCake 登入，設定好 Webhook，實際拿到 response 後才能測試。

只是一點建議，感謝～
